<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Mersal.Events</RootNamespace>
    <AssemblyName>Mersal.Events</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../audit-client/Mersal.Audit.Client.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" />
    <PackageReference Include="CloudNative.CloudEvents.SystemTextJson" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Tests/**/*.cs" />
    <None Remove="Tests/**/*" />
  </ItemGroup>
</Project>
