-- admin-service — 0007 time-bounded branch scope grants (phase 21.3, design 40 §3, ADR-0021).
--
-- Reach is not authority. Holding `orders:consume` says nothing about WHICH branch's orders, and 0004's
-- user_branch_assignment answers that as a permanent row someone has to remember to delete. "Doctor covering
-- Alexandria for October only" becomes a first-class, expiring, attributed fact here instead.
--
-- EXPAND ONLY. user_branch_assignment stays authoritative and is left completely untouched; this table is
-- populated FROM it and the two are kept in step until 21.5 contracts. Nothing about anyone's reach changes
-- on deploy — that is the acceptance criterion (row-parity), and the parity test asserts it.
--
-- TWO DIVERGENCES FROM THE PHASE PROMPT, both recorded in ADR-0021:
--
--   1. branch_id uuid, NOT branch_code. libs/auth's IBranchContext / BranchAssignment are Guid-keyed
--      throughout and admin.user_branch_assignment already stores branch_id uuid. Introducing a code-keyed
--      table would mean a lookup on every request and a second identifier for the same thing.
--   2. The grant carries BOTH subject_user_id and membership_id. The design keys reach on the MEMBERSHIP
--      (invariant 1), but memberships live in the identity schema and admin-service must not read across a
--      service boundary (the same rule that kept identity out of admin.tenant in 21.1). So the copy
--      preserves subject_user_id — authoritative today — and membership_id is left NULL for identity to
--      populate. Resolution prefers membership_id when present. 21.5 contracts to membership-only.

CREATE TABLE IF NOT EXISTS admin.branch_scope_grant (
    grant_id        uuid PRIMARY KEY,
    tenant_id       text        NOT NULL,
    -- The principal. membership_id is the target (design 40 §1); subject_user_id is what the expand phase
    -- can actually populate. Exactly one is required, and the CHECK makes a row with neither impossible —
    -- an unattributed grant is reach nobody can review.
    membership_id   uuid,
    subject_user_id text,
    branch_id       uuid        NOT NULL,   -- logical FK to provider.branch (value, not a cross-service FK)
    -- Home is still a property of the grant set: exactly one home per principal (design 37 §2.2).
    is_home         boolean     NOT NULL DEFAULT false,
    valid_from      date        NOT NULL,
    -- NULL = open-ended. Evaluated at RESOLUTION time; there is no sweeper, so a missed job can never leave
    -- reach switched on after it should have lapsed.
    valid_until     date,
    granted_by      text,
    granted_reason  varchar(300),
    is_deleted      boolean     NOT NULL DEFAULT false,
    row_version     integer     NOT NULL DEFAULT 0,
    created_by      text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      text,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_grant_has_a_principal CHECK (membership_id IS NOT NULL OR subject_user_id IS NOT NULL),
    CONSTRAINT ck_grant_window CHECK (valid_until IS NULL OR valid_until >= valid_from)
);

CREATE INDEX IF NOT EXISTS ix_bsg_membership ON admin.branch_scope_grant (membership_id) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_bsg_subject    ON admin.branch_scope_grant (tenant_id, subject_user_id) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_bsg_branch     ON admin.branch_scope_grant (branch_id) WHERE NOT is_deleted;

-- One live home branch per principal, mirroring 0004's ux_user_home_branch. Two homes would make step ③ of
-- the precedence chain ambiguous, and an ambiguous default silently moves someone between branches.
CREATE UNIQUE INDEX IF NOT EXISTS ux_bsg_home_per_subject
    ON admin.branch_scope_grant (tenant_id, subject_user_id)
    WHERE is_home AND NOT is_deleted AND subject_user_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS admin.branch_scope_grant_history (
    history_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grant_id        uuid        NOT NULL,
    tenant_id       text        NOT NULL,
    membership_id   uuid,
    subject_user_id text,
    branch_id       uuid        NOT NULL,
    is_home         boolean     NOT NULL,
    valid_from      date        NOT NULL,
    valid_until     date,
    is_deleted      boolean     NOT NULL,
    row_version     integer     NOT NULL,
    changed_by      text,
    changed_at      timestamptz NOT NULL DEFAULT now(),
    change_reason   text
);
CREATE INDEX IF NOT EXISTS ix_bsg_history_grant
    ON admin.branch_scope_grant_history (grant_id, changed_at DESC);

-- ---- Copy: every effective assignment becomes a grant -------------------------------------------------------
--
-- ROW PARITY is the acceptance criterion: no principal gains or loses a branch by migration alone. Revoked
-- assignments are copied as soft-deleted rather than skipped, so the grant table is a faithful record and a
-- later reconciliation can compare the two tables row for row instead of explaining absences.
--
-- IDEMPOTENT ON TWO KEYS, AND IT USED TO BE ONE.
--
-- The obvious guard is `NOT EXISTS (grant_id = assignment_id)`: an assignment already copied is not copied
-- again. That is correct and it is not sufficient, because the grant table has a SECOND uniqueness rule —
-- `ux_bsg_home_per_subject`, one live home per principal — keyed on (tenant_id, subject_user_id) rather than
-- on the id. The two keys disagree the moment a home assignment is RE-ISSUED: the app revokes the old row
-- and writes a new one with a fresh assignment_id, the id guard sees an uncopied assignment, and the insert
-- collides with the home grant copied from its predecessor.
--
-- What that cost: `tools/ci/apply-migrations.sh` runs under `set -e` and re-applies every file on every
-- pass, so from the first re-issued home onward the whole script aborted HERE — and every service after
-- admin alphabetically silently stopped receiving migrations. The symptom was orders- and pharmacy-service
-- integration tests failing on missing tables, several migrations away from the actual cause, on a database
-- that looked migrated.
--
-- So the second guard matches the INDEX's predicate rather than the row's identity. A re-issued home is
-- skipped, keeping the grant copied from its predecessor: same principal, same reach, which is what row
-- parity actually asserts. The grant_id then no longer equals the current assignment_id for that row — a
-- divergence the expand phase can carry, since 21.5 contracts this table to membership-keyed grants anyway
-- and the reconciliation compares reach, not surrogate keys.

INSERT INTO admin.branch_scope_grant (
    grant_id, tenant_id, subject_user_id, branch_id, is_home,
    valid_from, valid_until, is_deleted, granted_reason, created_by, created_at)
SELECT
    a.assignment_id,
    a.tenant_id,
    a.subject_user_id,
    a.branch_id,
    a.assignment_type = 'Home',
    a.valid_from,
    a.valid_to,
    a.status = 'Revoked',
    'copied from user_branch_assignment (21.3)',
    'migration:0007',
    now()
FROM admin.user_branch_assignment a
WHERE NOT EXISTS (
    SELECT 1 FROM admin.branch_scope_grant g WHERE g.grant_id = a.assignment_id)
  -- The home guard. Its condition is the index predicate written out: a row is only capable of colliding
  -- when it would itself be a LIVE HOME with a subject, so a revoked or additional assignment is never
  -- suppressed by it — the parity test asserts all four shapes still copy.
  AND NOT (
        a.assignment_type = 'Home'
    AND a.status <> 'Revoked'
    AND a.subject_user_id IS NOT NULL
    AND EXISTS (
        SELECT 1 FROM admin.branch_scope_grant g
         WHERE g.tenant_id       = a.tenant_id
           AND g.subject_user_id = a.subject_user_id
           AND g.is_home
           AND NOT g.is_deleted));

INSERT INTO admin.branch_scope_grant_history (
    grant_id, tenant_id, membership_id, subject_user_id, branch_id, is_home,
    valid_from, valid_until, is_deleted, row_version, changed_by, change_reason)
SELECT g.grant_id, g.tenant_id, g.membership_id, g.subject_user_id, g.branch_id, g.is_home,
       g.valid_from, g.valid_until, g.is_deleted, g.row_version, 'migration:0007',
       'copy from user_branch_assignment (21.3)'
FROM admin.branch_scope_grant g
WHERE g.created_by = 'migration:0007'
  AND NOT EXISTS (SELECT 1 FROM admin.branch_scope_grant_history h WHERE h.grant_id = g.grant_id);

-- ---- RLS + grants (0001/0005's model: tenant-isolated under the NOBYPASSRLS runtime role) --------------------

ALTER TABLE admin.branch_scope_grant         ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin.branch_scope_grant_history ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies
                   WHERE schemaname = 'admin' AND tablename = 'branch_scope_grant' AND policyname = 'rls_branch_scope_grant') THEN
        -- No GUC ⇒ no rows. Fail closed, exactly as 0005 established for every other admin table.
        CREATE POLICY rls_branch_scope_grant ON admin.branch_scope_grant
            USING (tenant_id = current_setting('app.tenant_id', true))
            WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies
                   WHERE schemaname = 'admin' AND tablename = 'branch_scope_grant_history' AND policyname = 'rls_bsg_history') THEN
        CREATE POLICY rls_bsg_history ON admin.branch_scope_grant_history
            USING (tenant_id = current_setting('app.tenant_id', true))
            WITH CHECK (tenant_id = current_setting('app.tenant_id', true));
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'hbmp_app') THEN
        GRANT SELECT, INSERT, UPDATE ON admin.branch_scope_grant         TO hbmp_app;
        GRANT SELECT, INSERT, UPDATE ON admin.branch_scope_grant_history TO hbmp_app;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA admin TO hbmp_app;
    END IF;
END $$;
