-- admin-service — 0008 program enablement: per-tenant features + live-counted caps
-- (phase 21.4, design 40 §4, adaptation A4).
--
-- A4 IS THE POINT: this is NOT commercial upsell. Mersal is a charity and its tenants are partner NGOs and
-- clinics, not customers on a price plan. These switches say "this organisation has been onboarded onto the
-- claims programme", and the caps exist so a partner cannot silently consume shared capacity. The copy the
-- SPA shows must never read like a paywall.
--
-- The third, ORTHOGONAL gate (design 40 §4): checked AFTER authorization, BEFORE execution. A fully
-- authorized principal can still be refused — and the refusal is a DIFFERENT problem type from a permission
-- denial, because the remedies differ. "Ask your administrator for the permission" and "ask Mersal to enable
-- the programme" send people down completely different paths, and conflating them wastes both.
--
-- Additive. Absence of a row means DISABLED for features (fail closed — a programme nobody has switched on
-- has not been switched on) and UNLIMITED for caps (fail open — inventing a limit nobody configured would
-- take a working platform offline the day this deploys).

CREATE TABLE IF NOT EXISTS admin.tenant_feature (
    tenant_id   text        NOT NULL,
    feature_key varchar(32) NOT NULL CHECK (feature_key IN (
        'claims', 'callcentre', 'interop', 'reporting_extracts', 'pharmacy',
        'orders', 'approvals', 'emr', 'finance', 'documents', 'case_management')),
    enabled     boolean     NOT NULL DEFAULT false,
    changed_by  text,
    changed_at  timestamptz NOT NULL DEFAULT now(),
    row_version integer     NOT NULL DEFAULT 0,
    PRIMARY KEY (tenant_id, feature_key)
);

CREATE TABLE IF NOT EXISTS admin.tenant_feature_history (
    history_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     text        NOT NULL,
    feature_key   varchar(32) NOT NULL,
    enabled       boolean     NOT NULL,
    changed_by    text,
    changed_at    timestamptz NOT NULL DEFAULT now(),
    change_reason text
);
CREATE INDEX IF NOT EXISTS ix_feature_history ON admin.tenant_feature_history (tenant_id, feature_key, changed_at DESC);

-- Caps. max_value is a COUNT of live rows, never a running total — see the enforcement note below.
CREATE TABLE IF NOT EXISTS admin.tenant_limit (
    tenant_id   text        NOT NULL,
    limit_key   varchar(32) NOT NULL CHECK (limit_key IN (
        'active_users', 'active_provider_users', 'monthly_extracts', 'storage_mb')),
    max_value   integer     NOT NULL CHECK (max_value >= 0),
    changed_by  text,
    changed_at  timestamptz NOT NULL DEFAULT now(),
    row_version integer     NOT NULL DEFAULT 0,
    PRIMARY KEY (tenant_id, limit_key)
);

CREATE TABLE IF NOT EXISTS admin.tenant_limit_history (
    history_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     text        NOT NULL,
    limit_key     varchar(32) NOT NULL,
    max_value     integer     NOT NULL,
    changed_by    text,
    changed_at    timestamptz NOT NULL DEFAULT now(),
    change_reason text
);
CREATE INDEX IF NOT EXISTS ix_limit_history ON admin.tenant_limit_history (tenant_id, limit_key, changed_at DESC);

-- ---- Enforcement note (design 40 §4) -------------------------------------------------------------------------
--
-- Limits are enforced by COUNTING LIVE ROWS inside the mutating transaction, never by a stored counter.
-- A counter drifts: every failed transaction, every restore, every row deleted by a path that forgot to
-- decrement leaves it wrong, and the direction of the error is unknowable afterwards. Counting is O(rows)
-- and these are small administrative sets. It also makes "delete a user and the slot frees immediately"
-- true by construction rather than by remembering to decrement.
--
-- Deliberately NO cached "remaining" column, for the same reason.

-- ---- RLS + grants (0005's fail-closed model) ------------------------------------------------------------------

ALTER TABLE admin.tenant_feature         ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin.tenant_feature_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin.tenant_limit           ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin.tenant_limit_history   ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE t text;
BEGIN
    FOREACH t IN ARRAY ARRAY['tenant_feature', 'tenant_feature_history', 'tenant_limit', 'tenant_limit_history']
    LOOP
        IF NOT EXISTS (SELECT 1 FROM pg_policies
                       WHERE schemaname = 'admin' AND tablename = t AND policyname = 'rls_' || t) THEN
            -- No GUC ⇒ no rows, exactly as 0005 established for every other admin table.
            EXECUTE format(
                'CREATE POLICY %I ON admin.%I USING (tenant_id = current_setting(''app.tenant_id'', true))
                 WITH CHECK (tenant_id = current_setting(''app.tenant_id'', true))', 'rls_' || t, t);
        END IF;
    END LOOP;
END $$;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'hbmp_app') THEN
        GRANT SELECT, INSERT, UPDATE ON admin.tenant_feature         TO hbmp_app;
        GRANT SELECT, INSERT, UPDATE ON admin.tenant_feature_history TO hbmp_app;
        GRANT SELECT, INSERT, UPDATE ON admin.tenant_limit           TO hbmp_app;
        GRANT SELECT, INSERT, UPDATE ON admin.tenant_limit_history   TO hbmp_app;
        GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA admin TO hbmp_app;
    END IF;
END $$;
