<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>Mersal.Profile.Tests</RootNamespace><IsPackable>false</IsPackable><IsTestProject>true</IsTestProject></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" /><PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" /><PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Domain/Mersal.Profile.Domain.csproj" />
    <ProjectReference Include="../Infrastructure/Mersal.Profile.Infrastructure.csproj" />
    <ProjectReference Include="../Api/Mersal.Profile.Api.csproj" />
    <ProjectReference Include="../../../libs/authz/Mersal.Authz.csproj" />
  </ItemGroup>
  <ItemGroup><Using Include="Xunit" /></ItemGroup>
</Project>
