<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>Mersal.Identity.Tests</RootNamespace><IsPackable>false</IsPackable><IsTestProject>true</IsTestProject></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" /><PackageReference Include="xunit" /><PackageReference Include="Xunit.SkippableFact" />
    <PackageReference Include="xunit.runner.visualstudio" /><PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Domain/Mersal.Identity.Domain.csproj" />
    <ProjectReference Include="../Infrastructure/Mersal.Identity.Infrastructure.csproj" />
    <ProjectReference Include="../Api/Mersal.Identity.Api.csproj" />
    <ProjectReference Include="../../../libs/auth/Mersal.Auth.csproj" />
  </ItemGroup>
  <ItemGroup><Using Include="Xunit" /></ItemGroup>
</Project>
