-- identity-service — Phase 17.1 (ADR-0015). The in-app identity store: ASP.NET Core Identity's user/role
-- tables over the `identity` schema, plus the roles/scopes-as-DATA model (scope catalog + role→scope matrix)
-- the OpenIddict issuer (17.2) reads to build the frozen token contract's `roles` + `scope` claims.
--
-- The repo applies hand-authored SQL (not EF migrations), so this DDL is the single source of truth and MUST
-- match IdentityStoreDbContext exactly (short snake_case table names, snake_case columns). Additive + idempotent.

CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- gen_random_uuid()
CREATE SCHEMA IF NOT EXISTS identity;

-- ---- ASP.NET Core Identity core (uuid keys) ---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS identity."user" (
    id                     uuid PRIMARY KEY,
    user_name              text,
    normalized_user_name   text,
    email                  text,
    normalized_email       text,
    email_confirmed        boolean NOT NULL DEFAULT false,
    password_hash          text,
    security_stamp         text,
    concurrency_stamp      text,
    phone_number           text,
    phone_number_confirmed boolean NOT NULL DEFAULT false,
    two_factor_enabled     boolean NOT NULL DEFAULT false,
    lockout_end            timestamptz,
    lockout_enabled        boolean NOT NULL DEFAULT true,
    access_failed_count    integer NOT NULL DEFAULT 0,
    -- Mersal extensions (ABAC claims + min-necessary identity):
    tenant_id              text NOT NULL DEFAULT '',
    provider_id            uuid,
    display_name           text NOT NULL DEFAULT '',
    is_active              boolean NOT NULL DEFAULT true,
    created_at             timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_user_normalized_user_name ON identity."user" (normalized_user_name);
CREATE INDEX IF NOT EXISTS ix_user_normalized_email ON identity."user" (normalized_email);
CREATE INDEX IF NOT EXISTS ix_user_tenant ON identity."user" (tenant_id);

CREATE TABLE IF NOT EXISTS identity.role (
    id                uuid PRIMARY KEY,
    name              text,
    normalized_name   text,
    concurrency_stamp text,
    sensitivity_tier  varchar(2) NOT NULL DEFAULT 'T1',
    description       text
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_role_normalized_name ON identity.role (normalized_name);

CREATE TABLE IF NOT EXISTS identity.user_role (
    user_id uuid NOT NULL REFERENCES identity."user"(id) ON DELETE CASCADE,
    role_id uuid NOT NULL REFERENCES identity.role(id)   ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);
CREATE INDEX IF NOT EXISTS ix_user_role_role ON identity.user_role (role_id);

CREATE TABLE IF NOT EXISTS identity.user_claim (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     uuid NOT NULL REFERENCES identity."user"(id) ON DELETE CASCADE,
    claim_type  text,
    claim_value text
);
CREATE INDEX IF NOT EXISTS ix_user_claim_user ON identity.user_claim (user_id);

CREATE TABLE IF NOT EXISTS identity.role_claim (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id     uuid NOT NULL REFERENCES identity.role(id) ON DELETE CASCADE,
    claim_type  text,
    claim_value text
);
CREATE INDEX IF NOT EXISTS ix_role_claim_role ON identity.role_claim (role_id);

CREATE TABLE IF NOT EXISTS identity.user_login (
    login_provider        text NOT NULL,
    provider_key          text NOT NULL,
    provider_display_name text,
    user_id               uuid NOT NULL REFERENCES identity."user"(id) ON DELETE CASCADE,
    PRIMARY KEY (login_provider, provider_key)
);
CREATE INDEX IF NOT EXISTS ix_user_login_user ON identity.user_login (user_id);

CREATE TABLE IF NOT EXISTS identity.user_token (
    user_id        uuid NOT NULL REFERENCES identity."user"(id) ON DELETE CASCADE,
    login_provider text NOT NULL,
    name           text NOT NULL,
    value          text,
    PRIMARY KEY (user_id, login_provider, name)
);

-- ---- Roles & scopes as DATA (17.1) ------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS identity.scope (
    name         varchar(64) PRIMARY KEY,
    domain       varchar(32) NOT NULL,
    description  text,
    service_only boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS identity.role_scope (
    role_name  varchar(64) NOT NULL,
    scope_name varchar(64) NOT NULL REFERENCES identity.scope(name) ON DELETE CASCADE,
    PRIMARY KEY (role_name, scope_name)
);
CREATE INDEX IF NOT EXISTS ix_role_scope_scope ON identity.role_scope (scope_name);

-- ---- Seed: scope catalog (frozen vocabulary, docs/security/token-contract.md §2) --------------------------

INSERT INTO identity.scope (name, domain, service_only) VALUES
    ('admin:read','admin',false), ('admin:write','admin',false), ('admin:break-glass','admin',false),
    ('orders:read','orders',false), ('orders:consume','orders',false), ('orders:write','orders',false),
    ('pharmacy:read','pharmacy',false), ('pharmacy:dispense','pharmacy',false),
    ('auth:read','auth',false), ('auth:review','auth',false), ('auth:decide','auth',false),
    ('auth:emergency','auth',false), ('auth:override','auth',false), ('auth:manual','auth',false),
    ('auth:ingest','auth',true),
    ('reception:search','reception',false),
    ('emr:read','emr',false), ('emr:write','emr',false), ('encounter:write','emr',false),
    ('rx:write','rx',false), ('patient:write','patient',false), ('eligibility:check','eligibility',false),
    ('appointment:read','appointment',false), ('appointment:write','appointment',false),
    -- Reservation without the arrival decisions: the call centre books across branches but must never check a
    -- patient in or mark a no-show, which stay behind appointment:write.
    ('appointment:reserve','appointment',false),
    ('document:write','document',false),
    ('case:read','case',false), ('case:write','case',false), ('case:manage','case',false),
    ('finance:read','finance',false), ('finance:write','finance',false), ('finance:approve','finance',false),
    ('finance:export','finance',false), ('finance:project','finance',false),
    ('provider:read','provider',false), ('provider:write','provider',false), ('provider:finance','provider',false),
    ('policy:write','policy',false), ('referral:write','referral',false),
    ('callcentre:read','callcentre',false), ('callcentre:act','callcentre',false),
    ('callcentre:interaction','callcentre',false), ('callcentre:verify','callcentre',false),
    ('claims:read','claims',false), ('claims:reconcile','claims',false), ('claims:export','claims',false),
    ('reporting:read','reporting',false), ('reporting:project','reporting',false), ('reporting:export','reporting',false),
    ('notification:read','notification',false), ('notification:ingest','notification',true),
    ('audit:read','audit',false)
ON CONFLICT (name) DO NOTHING;

-- ---- Seed: the 17 roles (tiers mirror services/admin/Domain/RoleCatalog.cs) -------------------------------

INSERT INTO identity.role (id, name, normalized_name, concurrency_stamp, sensitivity_tier)
SELECT gen_random_uuid(), r.name, upper(r.name), gen_random_uuid()::text, r.tier
FROM (VALUES
    ('reception','T1'), ('call_center','T2'), ('beneficiary_mgmt','T2'), ('finance','T2'),
    ('network_team','T2'), ('claims_officer','T2'), ('case_manager','T3'), ('doctor','T3'),
    ('nurse','T3'), ('lab_tech','T3'), ('imaging_tech','T3'), ('pharmacist','T3'),
    ('medical_approval','T3'), ('medical_director','T3'), ('provider_admin','T4'),
    ('org_admin','T4'), ('super_admin','T4')
) AS r(name, tier)
ON CONFLICT (normalized_name) DO NOTHING;

-- ---- Seed: role→scope matrix (11-permission-matrix §2/§3, mirrors apps/web permissions.ts) ---------------
-- Initial grants; the 17.4 admin surface manages these as data. Min-necessary hard rules hold structurally
-- (Reception/Finance/Claims carry NO emr/diagnosis scope; Lab carries NO pharmacy/rx scope; etc.).

INSERT INTO identity.role_scope (role_name, scope_name)
SELECT rs.role, rs.scope FROM (VALUES
    ('reception','reception:search'), ('reception','eligibility:check'),
    ('reception','appointment:read'), ('reception','appointment:write'), ('reception','notification:read'),

    ('call_center','callcentre:read'), ('call_center','callcentre:act'),
    ('call_center','callcentre:interaction'), ('call_center','callcentre:verify'),
    -- Reservation-only by construction: appointment:reserve books/reschedules/cancels, while check-in and
    -- no-show sit behind appointment:write, which the call centre deliberately does NOT hold.
    ('call_center','appointment:read'), ('call_center','appointment:reserve'),
    ('call_center','notification:read'),

    ('beneficiary_mgmt','patient:write'), ('beneficiary_mgmt','eligibility:check'),
    ('beneficiary_mgmt','notification:read'),

    ('finance','finance:read'), ('finance','finance:write'), ('finance','finance:approve'),
    ('finance','finance:export'), ('finance','finance:project'), ('finance','provider:finance'),
    ('finance','notification:read'),

    ('network_team','provider:read'), ('network_team','provider:write'),
    ('network_team','provider:finance'), ('network_team','notification:read'),

    ('claims_officer','claims:read'), ('claims_officer','claims:reconcile'),
    ('claims_officer','claims:export'), ('claims_officer','notification:read'),

    ('case_manager','case:read'), ('case_manager','case:write'), ('case_manager','case:manage'),
    ('case_manager','notification:read'),

    ('doctor','emr:read'), ('doctor','emr:write'), ('doctor','encounter:write'),
    ('doctor','orders:read'), ('doctor','orders:write'), ('doctor','rx:write'),
    ('doctor','referral:write'), ('doctor','appointment:read'), ('doctor','eligibility:check'),
    ('doctor','notification:read'),

    ('nurse','emr:read'), ('nurse','encounter:write'), ('nurse','appointment:read'),
    ('nurse','notification:read'),

    ('lab_tech','orders:read'), ('lab_tech','orders:consume'), ('lab_tech','notification:read'),
    ('imaging_tech','orders:read'), ('imaging_tech','orders:consume'), ('imaging_tech','notification:read'),

    ('pharmacist','pharmacy:read'), ('pharmacist','pharmacy:dispense'), ('pharmacist','notification:read'),

    ('medical_approval','auth:read'), ('medical_approval','auth:review'), ('medical_approval','auth:decide'),
    ('medical_approval','auth:manual'), ('medical_approval','auth:emergency'),
    ('medical_approval','notification:read'),

    ('medical_director','reporting:read'), ('medical_director','reporting:project'),
    ('medical_director','reporting:export'), ('medical_director','auth:read'),
    ('medical_director','notification:read'),

    ('provider_admin','provider:read'), ('provider_admin','provider:write'),
    ('provider_admin','notification:read'),

    ('org_admin','admin:read'), ('org_admin','admin:write'), ('org_admin','policy:write'),
    ('org_admin','reporting:read'), ('org_admin','reporting:project'), ('org_admin','reporting:export'),
    ('org_admin','audit:read'), ('org_admin','notification:read'),

    ('super_admin','admin:read'), ('super_admin','admin:write'), ('super_admin','admin:break-glass'),
    ('super_admin','policy:write'), ('super_admin','auth:override'), ('super_admin','audit:read'),
    ('super_admin','reporting:read'), ('super_admin','reporting:project'), ('super_admin','reporting:export'),
    ('super_admin','notification:read')
) AS rs(role, scope)
-- Conflict target left UNNAMED deliberately. This named `(role_name, scope_name)` — role_scope's primary key
-- at the time 0001 was written — but 0011 WIDENED that key to (tenant_id, role_name, scope_name). Postgres
-- resolves an ON CONFLICT target against the constraints that exist WHEN THE STATEMENT RUNS, so from 0011
-- onwards re-running 0001 failed with "there is no unique or exclusion constraint matching the ON CONFLICT
-- specification" — and since apply-migrations.sh runs with ON_ERROR_STOP, that aborted the whole identity
-- sequence and every LATER identity migration silently stopped being applied to an existing database.
--
-- Bare DO NOTHING matches whatever unique constraint the table currently has, so this statement is correct
-- both on a fresh database (narrow key) and on one that has reached 0011 (widened key). The rows are seed
-- grants inserted without tenant_id, which the column DEFAULT places in the '' bucket exactly as before, so
-- the widened key still recognises a re-run as a duplicate.
ON CONFLICT DO NOTHING;
