-- identity-service — 0010 tenant_membership: the security principal (phase 21.1, design 40 §1, ADR-0021).
--
-- Identity ≠ membership ≠ tenant. Today `identity."user"` carries tenant_id + provider_id and
-- `identity.user_role` binds roles to the USER, so one person is one principal with one blended authority.
-- A doctor who is also a provider-admin at a partner NGO cannot be expressed. This adds the join that IS the
-- principal: (identity × tenant) → membership, owning the roles, the provider binding, and the lifecycle.
--
-- Expand/contract: `user_role` and `user.provider_id` stay readable and authoritative until 21.2 flips the
-- evaluator onto memberships; this migration only ADDS and BACKFILLS. A follow-up contracts them.
--
-- DELIBERATELY NOT RLS-PROTECTED, for the reason 0002 records for identity."user": the issuer resolves a
-- login BY USERNAME to discover which tenants the identity belongs to, BEFORE any request-scoped
-- app.tenant_id exists. A tenant predicate here would make the membership chooser unable to read the very
-- rows it exists to list, i.e. it would break login. tenant_id in this schema is a CLAIM SOURCE, not a row
-- filter; isolation is enforced by every other service's RLS over its own data. (Design 40's "RLS like every
-- other tenant-scoped table" does not survive contact with the authentication path — see ADR-0021.)
--
-- The repo applies hand-authored SQL (not EF migrations), so this DDL must match IdentityStoreDbContext
-- exactly (short snake_case table names, snake_case columns). Additive + idempotent.

-- ---- The principal ----------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS identity.tenant_membership (
    membership_id  uuid PRIMARY KEY,
    user_id        uuid        NOT NULL REFERENCES identity."user"(id) ON DELETE CASCADE,
    tenant_id      text        NOT NULL,
    -- Provider ownership becomes a property of the MEMBERSHIP, not the identity (design 40 §1): the same
    -- person may be provider-bound in one tenant and staff in another.
    provider_id    uuid,
    status         varchar(10) NOT NULL DEFAULT 'Invited'
                   CHECK (status IN ('Invited', 'Active', 'Suspended', 'Ended')),
    -- uuid, not a branch CODE: libs/auth's IBranchContext/BranchAssignment are Guid-keyed throughout and
    -- admin.user_branch_assignment already stores branch_id uuid (ADR-0021 divergence table).
    home_branch_id uuid,
    invited_at     timestamptz,
    activated_at   timestamptz,
    ended_at       timestamptz,
    -- House style: soft-delete + optimistic concurrency + attribution (CLAUDE.md § Audit — no hard deletes).
    is_deleted     boolean     NOT NULL DEFAULT false,
    row_version    integer     NOT NULL DEFAULT 0,
    created_by     text,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_by     text,
    updated_at     timestamptz NOT NULL DEFAULT now()
);

-- THE INVARIANT: one live membership per (identity, tenant). Two memberships in the same tenant would make
-- "the active membership" ambiguous, and invariant 1 says authorization evaluates against exactly one.
CREATE UNIQUE INDEX IF NOT EXISTS ux_membership_user_tenant
    ON identity.tenant_membership (user_id, tenant_id) WHERE NOT is_deleted;

CREATE INDEX IF NOT EXISTS ix_membership_user   ON identity.tenant_membership (user_id) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS ix_membership_tenant ON identity.tenant_membership (tenant_id, status) WHERE NOT is_deleted;

-- ---- Roles, bound to the membership rather than the identity ------------------------------------------------

CREATE TABLE IF NOT EXISTS identity.membership_role (
    membership_id uuid        NOT NULL REFERENCES identity.tenant_membership(membership_id) ON DELETE CASCADE,
    role_id       uuid        NOT NULL REFERENCES identity.role(id) ON DELETE CASCADE,
    granted_by    text,
    granted_at    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (membership_id, role_id)
);
CREATE INDEX IF NOT EXISTS ix_membership_role_role ON identity.membership_role (role_id);

-- ---- History twin (append-only; the principal's lifecycle is audit evidence) ---------------------------------

CREATE TABLE IF NOT EXISTS identity.tenant_membership_history (
    history_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_id  uuid        NOT NULL,
    user_id        uuid        NOT NULL,
    tenant_id      text        NOT NULL,
    provider_id    uuid,
    status         varchar(10) NOT NULL,
    home_branch_id uuid,
    is_deleted     boolean     NOT NULL,
    row_version    integer     NOT NULL,
    changed_by     text,
    changed_at     timestamptz NOT NULL DEFAULT now(),
    change_reason  text
);
CREATE INDEX IF NOT EXISTS ix_membership_history_membership
    ON identity.tenant_membership_history (membership_id, changed_at DESC);

-- ---- Platform administration flag (adaptation A1) ------------------------------------------------------------

-- A1: this is a PLATFORM-ADMINISTRATION flag, never a PHI wildcard. 21.2's evaluator short-circuits ONLY
-- catalog keys marked is_platform_admin_key and hard-excludes everything else; it does not bypass field
-- projection, ABAC conditions, RLS, branch scope, or the sensitive gate. Break-glass stays the only elevation
-- into clinical data. Granting it is itself an audited, platform-admin-only act.
ALTER TABLE identity."user" ADD COLUMN IF NOT EXISTS is_platform_admin boolean NOT NULL DEFAULT false;

-- ---- Backfill: every existing user_role row becomes a membership role -----------------------------------------
--
-- SNAPSHOT PARITY is the acceptance criterion (21.1): no user may gain or lose access by migration alone.
-- Every user gets exactly one membership — in the tenant they already belong to — carrying exactly the roles
-- they already hold and the provider_id they already have. Nothing is invented and nothing is dropped.
-- Idempotent: re-running inserts nothing new (guarded by the unique index and NOT EXISTS).

INSERT INTO identity.tenant_membership (
    membership_id, user_id, tenant_id, provider_id, status, activated_at, created_by, created_at)
SELECT
    gen_random_uuid(),
    u.id,
    u.tenant_id,
    u.provider_id,
    -- is_active is the identity-level deactivation switch (0001). A disabled account keeps its membership but
    -- must not be selectable, so it lands Suspended rather than Active — de-provisioning semantics unchanged.
    CASE WHEN u.is_active THEN 'Active' ELSE 'Suspended' END,
    CASE WHEN u.is_active THEN u.created_at END,
    'migration:0010',
    now()
FROM identity."user" u
WHERE NOT EXISTS (
    SELECT 1 FROM identity.tenant_membership m
    WHERE m.user_id = u.id AND m.tenant_id = u.tenant_id AND NOT m.is_deleted);

INSERT INTO identity.membership_role (membership_id, role_id, granted_by)
SELECT m.membership_id, ur.role_id, 'migration:0010'
FROM identity.user_role ur
JOIN identity."user" u            ON u.id = ur.user_id
JOIN identity.tenant_membership m ON m.user_id = ur.user_id AND m.tenant_id = u.tenant_id AND NOT m.is_deleted
WHERE NOT EXISTS (
    SELECT 1 FROM identity.membership_role mr
    WHERE mr.membership_id = m.membership_id AND mr.role_id = ur.role_id);

INSERT INTO identity.tenant_membership_history (
    membership_id, user_id, tenant_id, provider_id, status, home_branch_id,
    is_deleted, row_version, changed_by, change_reason)
SELECT m.membership_id, m.user_id, m.tenant_id, m.provider_id, m.status, m.home_branch_id,
       m.is_deleted, m.row_version, 'migration:0010', 'backfill from user_role (21.1)'
FROM identity.tenant_membership m
WHERE m.created_by = 'migration:0010'
  AND NOT EXISTS (
    SELECT 1 FROM identity.tenant_membership_history h WHERE h.membership_id = m.membership_id);

-- ---- Grants (0002's model: the schema is reachable by identity-service under hbmp_app) -------------------------

GRANT SELECT, INSERT, UPDATE, DELETE ON identity.tenant_membership         TO hbmp_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON identity.membership_role           TO hbmp_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON identity.tenant_membership_history TO hbmp_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA identity TO hbmp_app;
