-- identity-service — 0014 session/device controls + login-attempt history (phase 21.5, design 40 §6, A6).
--
-- Two tables, and they answer two different questions that get confused:
--   user_session  — "what is currently able to act as me, and can I stop it?"
--   login_attempt — "who has been trying to be me, and did they succeed?"
--
-- NO CREDENTIAL MATERIAL. Neither table holds a password, a hash, a TOTP secret or a recovery code, and
-- login_attempt deliberately stores the ATTEMPTED USERNAME rather than anything typed alongside it. This is
-- enforced by NoCredentialMaterialInAuditTests, not just by intent: these rows are retained for years and
-- are readable by administrators who may not see clinical data.

CREATE TABLE IF NOT EXISTS identity.user_session (
    session_id     uuid PRIMARY KEY,
    user_id        uuid        NOT NULL REFERENCES identity."user"(id) ON DELETE CASCADE,
    -- The membership the session is acting under (21.1c). Null only for a legacy membership-less session.
    membership_id  uuid,
    -- Device metadata for recognition, NOT for authentication. A user identifying their own sessions needs
    -- "Firefox on Windows, Cairo, since Tuesday" — enough to spot the one that is not theirs.
    user_agent     varchar(400),
    ip_address     inet,
    created_at     timestamptz NOT NULL DEFAULT now(),
    last_seen_at   timestamptz NOT NULL DEFAULT now(),
    -- Revocation is a soft, attributed act; the row survives so "who ended this session and when" is
    -- answerable afterwards (CLAUDE.md § Audit — no hard deletes).
    revoked_at     timestamptz,
    revoked_by     text,
    revoke_reason  varchar(200)
);

-- The hot query is "this identity's live sessions", for the list, the cap, and revoke-all.
CREATE INDEX IF NOT EXISTS ix_session_user_live
    ON identity.user_session (user_id, created_at DESC) WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS identity.login_attempt (
    attempt_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Null when the username did not resolve: the attempt still matters (it is how credential stuffing
    -- looks), but there is no identity to attach it to.
    user_id          uuid REFERENCES identity."user"(id) ON DELETE SET NULL,
    -- What was typed in the username box. Never what was typed in the password box.
    username_tried   varchar(256) NOT NULL,
    succeeded        boolean     NOT NULL,
    -- A COARSE reason. Deliberately not "no such user" vs "wrong password" in anything the client sees —
    -- that distinction is a user-enumeration oracle. Stored coarse so it cannot leak by being surfaced.
    failure_reason   varchar(40),
    ip_address       inet,
    user_agent       varchar(400),
    attempted_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_login_attempt_user ON identity.login_attempt (user_id, attempted_at DESC);
CREATE INDEX IF NOT EXISTS ix_login_attempt_time ON identity.login_attempt (attempted_at DESC);

GRANT SELECT, INSERT, UPDATE ON identity.user_session  TO hbmp_app;
GRANT SELECT, INSERT         ON identity.login_attempt TO hbmp_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA identity TO hbmp_app;
