<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>Mersal.Admin.Tests</RootNamespace><IsPackable>false</IsPackable><IsTestProject>true</IsTestProject></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" /><PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" /><PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Api/Mersal.Admin.Api.csproj" />
    <ProjectReference Include="../Domain/Mersal.Admin.Domain.csproj" />
    <ProjectReference Include="../Infrastructure/Mersal.Admin.Infrastructure.csproj" />
    <ProjectReference Include="../../../libs/authz/Mersal.Authz.csproj" />
    <ProjectReference Include="../../../libs/audit-client/Mersal.Audit.Client.csproj" />
  </ItemGroup>
  <ItemGroup><Using Include="Xunit" /></ItemGroup>
</Project>
