<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Mersal.BenefitPricing</RootNamespace>
    <AssemblyName>Mersal.BenefitPricing</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../money/Mersal.Money.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Tests/**/*.cs" />
    <None Remove="Tests/**/*" />
  </ItemGroup>
</Project>
