<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>Mersal.Orders.Infrastructure</RootNamespace></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Domain/Mersal.Orders.Domain.csproj" />
    <ProjectReference Include="../../../libs/events/Mersal.Events.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="EFCore.NamingConventions" />
  </ItemGroup>
</Project>
