<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Mersal.MasterData.Loader</RootNamespace>
    <AssemblyName>masterdata-loader</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../services/masterdata/Domain/Mersal.MasterData.Domain.csproj" />
    <ProjectReference Include="../../services/masterdata/Infrastructure/Mersal.MasterData.Infrastructure.csproj" />
    <ProjectReference Include="../../libs/audit-client/Mersal.Audit.Client.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
</Project>
