using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using Mersal.Claims.Domain;

namespace Mersal.Claims.Infrastructure;

/// <summary>The rendered settlement-advice file + its metadata.</summary>
public sealed record RenderedFile(string Format, string ContentType, string FileName, byte[] Bytes);

/// <summary>Renders a settlement-advice projection to CSV (finance), XLSX (finance), or PDF (provider) with NO external
/// dependencies (self-hostable, $0 licensing). The projection carries only codes + amounts + coded reasons, so no
/// clinical field can appear in any output — asserted by a content test that parses the generated bytes. The canonical
/// CSV bytes are also the input to the content hash, so a stored document that changes is detectable.</summary>
public static class SettlementRenderer
{
    public static readonly string[] Header =
        ["ClaimNo", "CodeSystem", "Code", "Quantity", "BilledAmount", "ContractPrice", "AllowedAmount",
         "AdjustedDelta", "Status", "ReasonCodes"];

    public static string Canonical(SettlementProjection p) => BuildCsv(p);

    public static string ContentHash(SettlementProjection p)
    {
        var bytes = Encoding.UTF8.GetBytes(Canonical(p));
        return Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant();
    }

    public static RenderedFile Render(SettlementProjection p, string format) => format.ToUpperInvariant() switch
    {
        "CSV" => new RenderedFile("CSV", "text/csv", $"settlement-{p.BatchNo}-v{p.Version}.csv", Encoding.UTF8.GetBytes(BuildCsv(p))),
        "XLSX" => new RenderedFile("XLSX", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", $"settlement-{p.BatchNo}-v{p.Version}.xlsx", BuildXlsx(p)),
        "PDF" => new RenderedFile("PDF", "application/pdf", $"settlement-{p.BatchNo}-v{p.Version}.pdf", BuildPdf(p)),
        _ => throw new ArgumentOutOfRangeException(nameof(format), format, "Supported: CSV, XLSX, PDF"),
    };

    private static IReadOnlyList<string[]> DataRows(SettlementProjection p)
    {
        var rows = new List<string[]> { Header };
        foreach (var l in p.Lines)
            rows.Add([l.ClaimNo, l.CodeSystem, l.Code, l.Quantity.ToString(), l.BilledAmount.ToString(),
                l.ContractPrice?.ToString() ?? "", l.AllowedAmount?.ToString() ?? "", l.AdjustedDelta.ToString(),
                l.LineStatus, string.Join('|', l.ReasonCodes)]);
        return rows;
    }

    // ---- CSV --------------------------------------------------------------------------------------------
    private static string BuildCsv(SettlementProjection p)
    {
        var sb = new StringBuilder();
        sb.Append("SettlementAdvice,").Append(p.BatchNo).Append(",v").Append(p.Version).Append('\n');
        sb.Append("Payee,").Append(p.PayeeProviderId?.ToString() ?? "reimbursement-cohort")
          .Append(",Period,").Append(p.PeriodFrom).Append("..").Append(p.PeriodTo).Append('\n');
        sb.Append("GeneratedBy,").Append(Csv(p.GeneratedBy)).Append(',').Append(p.GeneratedAt.ToString("O")).Append('\n');
        foreach (var r in DataRows(p)) sb.Append(string.Join(',', r.Select(Csv))).Append('\n');
        sb.Append("Totals,Claimed,").Append(p.TotalClaimed).Append(",Priced,").Append(p.TotalPriced)
          .Append(",Approved,").Append(p.TotalApproved).Append(",Adjustments,").Append(p.TotalAdjusted)
          .Append(",Denied,").Append(p.TotalDenied).Append(",NetPayable,").Append(p.NetPayable).Append('\n');
        return sb.ToString();
    }

    private static string Csv(string v)
    {
        if (v.Contains(',') || v.Contains('"') || v.Contains('\n'))
            return "\"" + v.Replace("\"", "\"\"") + "\"";
        return v;
    }

    // ---- XLSX (minimal OPC package, no library) ---------------------------------------------------------
    private static byte[] BuildXlsx(SettlementProjection p)
    {
        using var ms = new MemoryStream();
        using (var zip = new ZipArchive(ms, ZipArchiveMode.Create, true))
        {
            Write(zip, "[Content_Types].xml",
                "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>" +
                "<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">" +
                "<Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/>" +
                "<Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/>" +
                "<Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/>" +
                "</Types>");
            Write(zip, "_rels/.rels",
                "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>" +
                "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">" +
                "<Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/>" +
                "</Relationships>");
            Write(zip, "xl/_rels/workbook.xml.rels",
                "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>" +
                "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">" +
                "<Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/>" +
                "</Relationships>");
            Write(zip, "xl/workbook.xml",
                "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>" +
                "<workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" " +
                "xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\">" +
                "<sheets><sheet name=\"Settlement\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>");

            var sb = new StringBuilder();
            sb.Append("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>")
              .Append("<worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><sheetData>");
            var rows = DataRows(p).ToList();
            rows.Add(["Totals", "", "", "", p.TotalClaimed.ToString(), p.TotalPriced.ToString(),
                p.TotalApproved.ToString(), p.TotalAdjusted.ToString(), p.TotalDenied.ToString(), p.NetPayable.ToString()]);
            for (var i = 0; i < rows.Count; i++)
            {
                sb.Append("<row r=\"").Append(i + 1).Append("\">");
                foreach (var cell in rows[i])
                    sb.Append("<c t=\"inlineStr\"><is><t xml:space=\"preserve\">").Append(Xml(cell)).Append("</t></is></c>");
                sb.Append("</row>");
            }
            sb.Append("</sheetData></worksheet>");
            Write(zip, "xl/worksheets/sheet1.xml", sb.ToString());
        }
        return ms.ToArray();
    }

    private static void Write(ZipArchive zip, string path, string content)
    {
        var entry = zip.CreateEntry(path, CompressionLevel.Optimal);
        using var s = entry.Open();
        var bytes = Encoding.UTF8.GetBytes(content);
        s.Write(bytes, 0, bytes.Length);
    }

    private static string Xml(string v) =>
        v.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    // ---- PDF (minimal single-page, no library) ----------------------------------------------------------
    private static byte[] BuildPdf(SettlementProjection p)
    {
        var lines = new List<string> { $"Settlement Advice {p.BatchNo} v{p.Version}",
            $"Payee {p.PayeeProviderId?.ToString() ?? "reimbursement-cohort"}  Period {p.PeriodFrom}..{p.PeriodTo}",
            $"Generated {p.GeneratedBy} {p.GeneratedAt:O}", "" };
        foreach (var r in DataRows(p)) lines.Add(string.Join("  |  ", r));
        lines.Add("");
        lines.Add($"Totals Claimed {p.TotalClaimed} Priced {p.TotalPriced} Approved {p.TotalApproved} " +
                  $"Adjustments {p.TotalAdjusted} Denied {p.TotalDenied} NetPayable {p.NetPayable}");

        var content = new StringBuilder("BT /F1 9 Tf 40 800 Td 12 TL ");
        foreach (var line in lines) content.Append('(').Append(PdfEsc(line)).Append(") Tj T* ");
        content.Append("ET");
        var stream = content.ToString();

        var objs = new List<string>
        {
            "<</Type/Catalog/Pages 2 0 R>>",
            "<</Type/Pages/Kids[3 0 R]/Count 1>>",
            "<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 842]/Contents 4 0 R/Resources<</Font<</F1 5 0 R>>>>>>",
            $"<</Length {Encoding.UTF8.GetByteCount(stream)}>>\nstream\n{stream}\nendstream",
            "<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>",
        };

        var sb = new StringBuilder();
        sb.Append("%PDF-1.4\n");
        var offsets = new List<int>();
        for (var i = 0; i < objs.Count; i++)
        {
            offsets.Add(Encoding.UTF8.GetByteCount(sb.ToString()));
            sb.Append(i + 1).Append(" 0 obj\n").Append(objs[i]).Append("\nendobj\n");
        }
        var xrefPos = Encoding.UTF8.GetByteCount(sb.ToString());
        sb.Append("xref\n0 ").Append(objs.Count + 1).Append('\n');
        sb.Append("0000000000 65535 f \n");
        foreach (var off in offsets) sb.Append(off.ToString("D10")).Append(" 00000 n \n");
        sb.Append("trailer\n<</Size ").Append(objs.Count + 1).Append("/Root 1 0 R>>\nstartxref\n").Append(xrefPos).Append("\n%%EOF");
        return Encoding.UTF8.GetBytes(sb.ToString());
    }

    private static string PdfEsc(string v) =>
        v.Replace("\\", "\\\\").Replace("(", "\\(").Replace(")", "\\)");
}
