<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><RootNamespace>Mersal.Interop.Infrastructure</RootNamespace></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Domain/Mersal.Interop.Domain.csproj" />
    <ProjectReference Include="../../../libs/events/Mersal.Events.csproj" />
    <ProjectReference Include="../../../libs/data/Mersal.Data.csproj" />
    <ProjectReference Include="../../../libs/audit-client/Mersal.Audit.Client.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="EFCore.NamingConventions" />
  </ItemGroup>
  <ItemGroup><None Update="Migrations/*.sql" CopyToOutputDirectory="PreserveNewest" /></ItemGroup>
</Project>
