<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Mersal.Authz</RootNamespace>
    <AssemblyName>Mersal.Authz</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../auth/Mersal.Auth.csproj" />
    <ProjectReference Include="../audit-client/Mersal.Audit.Client.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Tests/**/*.cs" />
    <None Remove="Tests/**/*" />
  </ItemGroup>
</Project>
